"""Build paper/supplement.tex from analysis CSVs so every supplement number is generated, not transcribed."""
import os
import re

import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
A = os.path.join(ROOT, "analysis")
OUT = os.path.join(ROOT, "paper", "supplement.tex")
NAMES = {"gpt-5": "gpt-5", "haiku-4.5": "Claude Haiku 4.5", "gemini-2.5-flash": "Gemini 2.5 Flash", "sonnet-5.5": "Claude Sonnet 5.5"}


def esc(x: object) -> str:
    return str(x).replace("\\", "").replace("$", r"\$").replace("&", r"\&").replace("%", r"\%").replace("_", r"\_").replace("#", r"\#")


def name(row: str) -> str:
    for k, v in NAMES.items():
        row = row.replace(k, v)
    return esc(row.replace("title-only", "title only"))


def table(df: pd.DataFrame, cols: list[tuple[str, str, str]], caption: str) -> str:
    spec = "".join("l" if fmt == "name" else "r" for _, _, fmt in cols)
    lines = [r"\begin{table}[h]\centering\small", rf"\caption{{{caption}}}", rf"\begin{{tabular}}{{{spec}}}", r"\toprule",
             " & ".join(h for _, h, _ in cols) + r" \\", r"\midrule"]
    for _, r in df.iterrows():
        cells = []
        for c, _, fmt in cols:
            v = r[c]
            cells.append(name(v) if fmt == "name" else ("--" if pd.isna(v) else format(v, fmt)))
        lines.append(" & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def prereg_text() -> str:
    log = open(os.path.join(ROOT, "LOG.md")).read()
    start = log.index("### 2026-10-09, PRE-REGISTRATION")
    nxt = log.find("\n### ", start + 10)
    end = nxt if nxt != -1 else len(log)
    body = log[start:end].split("\n", 1)[1].strip()
    body = body.replace("Rahul's", "[the author's]").replace("Rahul", "[the author]")
    body = re.sub(r"\*\*(.*?)\*\*", r"\\textbf{\1}", esc(body))
    body = body.replace("`", "")
    items = [ln[2:] for ln in body.splitlines() if ln.startswith("- ")]
    return "\\begin{itemize}\\small\n" + "\n".join(f"\\item {i}" for i in items) + "\n\\end{itemize}\n"


def main() -> None:
    clean = open(os.path.join(A, "02_clean.md")).read()
    steps = re.findall(r"^\| (\d[a-z]?\. .*?|raw rows)\s*\|\s*(\d+) \|\s*(\d+) \|", clean, re.M)
    steps_df = pd.DataFrame(steps, columns=["step", "remaining", "removed"]).astype({"remaining": int, "removed": int})
    short = ["raw rows", "unreadable image, missing score or date", "blank image (grayscale SD < 2)", "chart type empty / none / Other",
             "short side < 300 px", "score < 5", "near-duplicate (pHash <= 2) or placeholder group"]
    steps_df["step"] = short[: len(steps_df)]

    main_t = pd.read_csv(os.path.join(A, "08_main_table.csv"))
    sub = main_t[main_t["row"].str.contains("P2|P3|title-only|baseline") | (main_t["set"] == "close")].copy()
    contrasts = pd.read_csv(os.path.join(A, "08_prompt_contrasts.csv"))
    cal = pd.read_csv(os.path.join(A, "05_calibration.csv"))
    cal1 = pd.read_csv(os.path.join(A, "05_calibration_P1.csv"))
    spear = pd.read_csv(os.path.join(A, "08c_expert_vs_audience_spearman.csv"))
    fresh = pd.read_csv(os.path.join(A, "08c_equivalence.csv"))
    split = pd.read_csv(os.path.join(A, "07_cutoff_split.csv"))
    recog = pd.read_csv(os.path.join(A, "07_recognition_summary.csv"))

    parts = [r"""\documentclass[10pt]{article}
\usepackage[margin=1in]{geometry}
\usepackage{fontspec}
\setmainfont{texgyretermes}[Extension=.otf, UprightFont=*-regular, BoldFont=*-bold, ItalicFont=*-italic, BoldItalicFont=*-bolditalic]
\usepackage{booktabs}
\usepackage{caption}
\title{Supplement: LLM Chart Judges Reward Labels, Audiences Reward Topics}
\date{}
\begin{document}
\maketitle
All tables are generated by \texttt{src/11\_supplement.py} from the CSVs in \texttt{analysis/}. Pairs and prompts are identical to the main paper unless stated.

\section*{S1. Data cleaning}
Filters in order (\texttt{src/02\_clean.py}). Deviations from our original plan:
(i) a new filter for blank images (grayscale SD $<$ 2), which are video thumbnails labeled from their titles;
(ii) the perceptual-hash duplicate threshold was tightened from Hamming 4 to 2, because visual QA showed that distance-4 matches were different charts with shared layouts;
(iii) a new rule drops groups of 3 or more near-duplicates whose titles are unrelated (median token-set similarity $<$ 60), which removes link previews and site banners;
(iv) transparent images are composited on white.
No rule uses votes.
"""]
    parts.append(table(steps_df, [("step", "Step", "name"), ("remaining", "Rows remaining", "d"), ("removed", "Removed", "d")], "Cleaning funnel."))

    parts.append(r"\section*{S2. Other prompts, title-only control, close pairs}" + "\n"
                 r"P2 is a six-dimension VisJudge-style rubric (1--5 each, averaged). P3 is a pairwise prompt run in both orders: credit 1 if both orders pick the winner, 0 if both pick the loser, 0.5 if they disagree. The title-only control asks gpt-5 which of two titles got more upvotes, in both orders. These rows come from the earlier, smaller runs: P3 on the first 250 or 500 clear pairs, P2 on the first 150, and close pairs (vote ratio 1.5--2.5) on 200. $\Delta$ is the judge minus the image-blind baseline on the same pairs (95\% bootstrap CI)." + "\n")
    parts.append(table(sub, [("set", "Set", "name"), ("row", "Row", "name"), ("n_pairs", "$n$", "d"), ("accuracy", "Acc.", ".3f"), ("diff_vs_baseline", r"$\Delta$", "+.3f"),
                             ("diff_lo", "lo", "+.3f"), ("diff_hi", "hi", "+.3f"), ("inconsistency_rate", "Order flips", ".2f"), ("picks_first_shown_rate", "Picks first", ".2f")],
                       "Rubric (P2), pairwise (P3), title-only, and close-pair results."))
    parts.append(table(contrasts, [("contrast", "Paired contrast (same pairs)", "name"), ("n_pairs", "$n$", "d"), ("diff", "Diff.", "+.3f"), ("lo", "lo", "+.3f"), ("hi", "hi", "+.3f")],
                       "Prompt contrasts. The rubric and pairwise formats do not beat holistic P1, and images do not beat titles for gpt-5."))
    fr = fresh[fresh["subset"] == "pairs 501-2,000 (fresh)"]
    parts.append(table(fr, [("comparison", "Comparison (P1, 1,500 fresh pairs)", "name"), ("n_pairs", "$n$", "d"), ("diff", "Diff.", "+.4f"), ("ci90_lo", "90\\% lo", "+.4f"),
                            ("ci90_hi", "90\\% hi", "+.4f"), ("tost_p", "TOST $p$", ".3f"), ("verdict_margin_4pts", "Verdict", "name")],
                       "Robustness check: P1 equivalence on the 1,500 pairs no judge saw during development."))

    parts.append(r"\section*{S3. Calibration on VisJudge-Bench}" + "\n"
                 r"150 single-view items sampled with seed 20261008. P2 rubric mean vs.\ expert \texttt{overall\_score}. Published values (VisJudge-Bench v3, 648-item test split over all types): GPT-5 $r=0.428$, MAE 0.553. The test split cannot be reconstructed from the released file, so the comparison is approximate." + "\n")
    parts.append(table(cal, [("judge", "Judge", "name"), ("n_ok", "$n$", "d"), ("pearson_r", "Pearson $r$", ".3f"), ("r_lo", "lo", ".3f"), ("r_hi", "hi", ".3f"), ("mae", "MAE", ".3f")],
                       "P2 calibration against expert ratings."))
    m = spear.merge(cal1[["judge", "spearman_P1_vs_expert"]], on="judge", how="left", suffixes=("", "_cal"))
    parts.append(table(m, [("judge", "Judge", "name"), ("spearman_P1_vs_expert_cal", r"P1 $\rho$ vs.\ experts", ".3f"), ("n_audience_images", "Audience images", "d"),
                           ("spearman_P1_vs_audience_pct", r"P1 $\rho$ vs.\ audience pct", ".3f"), ("aud_lo", "lo", ".3f"), ("aud_hi", "hi", ".3f")],
                       "Same prompt (P1), same metric (Spearman), different targets. Sonnet 5.5 was not run on calibration items because of the budget cap."))

    parts.append(r"\section*{S4. Memorization}" + "\n"
                 r"Training cutoffs: gpt-5 2024-09-30, Claude Haiku 4.5 Feb 2025 (reliable), Gemini 2.5 Flash Jan 2025. The dataset ends Jan 2025, so only gpt-5 has post-cutoff pairs. The recognition probe asked each judge whether it had seen each of the 50 most-voted charts and, if so, for the title. Because 72\% of these charts print their title, recalls that match the chart's own OCR text are not counted as memory." + "\n")
    parts.append(table(split, [("judge", "Judge", "name"), ("prompt", "Prompt", "name"), ("group", "Cutoff group", "name"), ("n_pairs", "$n$", "d"), ("accuracy", "Acc.", ".3f"), ("lo", "lo", ".3f"), ("hi", "hi", ".3f")],
                       "Accuracy by training-cutoff group (first 500 clear pairs)."))
    parts.append(table(recog, [("judge", "Judge", "name"), ("n", "$n$", "d"), ("claimed_seen", "Claims seen", ".2f"), ("recall_rate", "Title recall (raw)", ".2f"),
                               ("recall_not_in_image_rate", "Recall not in image", ".2f")], "Recognition probe."))

    parts.append(r"\section*{S5. Pre-registration (verbatim from the project log, written before the 2,000-pair run; names redacted)}" + "\n" + prereg_text())
    parts.append(r"\end{document}")
    open(OUT, "w").write("\n".join(parts))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
